apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: shadidevsecops/web-app:docker_tag
        command: ["/bin/sh"]
        args: ["-c","sh /usr/local/tomcat/bin/startup.sh;while true; do echo hello; sleep 10;done"]
        ports:
            - name: http
              containerPort: 8080
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  labels:
    app: web-app
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31884
    protocol: TCP
    name: http
  selector:
    app: web-app